### ISSUE TITLE
Disable nftables service

### ISSUE THREAD

**Issue by myllynen** [linux-system-roles/firewall#136]
When using the firewall role only the firewalld service, not nftables, should be running to avoid any conflicts. While it's trivial to disable/mask nftables in a separate task it would be nice to have the role to do the same and thus avoid any risk for issues. Thanks.

**Comment by BrennanPaciorek** [comment]
Recent PR added the variable `firewall_disable_conflicting_services` that can be set to check for and disable any conflicting services (currently disables iptables, nftables, and ufw). You will want to enable this on your first task running the role in each playbook. Thank you for reporting this issue.
