### ISSUE TITLE
Overwite /etc/firewalld.conf on previous replaced instead of deleting it

### ISSUE THREAD

**Issue by BrennanPaciorek** [linux-system-roles/firewall#164]
**What would you like to be added**:

Overwriting of changed directives in /etc/firewalld.conf, instead of deleting firewalld.conf if it is different from the default configuration file.

**Why is this needed**:

When /etc/firewalld.conf is deleted, comments describing its directives are also removed (see issue #127).

**Comment by richm** [comment]
@BrennanPaciorek is this done?  If so, please add a link to the PR and close it
