### ISSUE TITLE
Update ansible-galaxy

### ISSUE THREAD

**Issue by tuxpeople** [linux-system-roles/firewall#31]
Hi

Galaxy has the last import of this role 2 yrs ago:
https://galaxy.ansible.com/linux-system-roles/firewall

Could you please update Galaxy? I had issues with the role from Galaxy and they are already fixed here in Github.

Thanks & br
Thomas

**Comment by richm** [comment]
> Hi
> 
> Galaxy has the last import of this role 2 yrs ago:
> https://galaxy.ansible.com/linux-system-roles/firewall
> 
> Could you please update Galaxy? I had issues with the role from Galaxy and they are already fixed here in Github.
> 
> Thanks & br
> Thomas

Can you use the collection instead?  https://galaxy.ansible.com/fedora/linux_system_roles

**Comment by tuxpeople** [comment]
Yes I can, thanks! Maybe you should remove the outdated role from Galaxy
