### ISSUE TITLE
Ansible as only source-of-truth

### ISSUE THREAD

**Issue by chrispoupart** [linux-system-roles/firewall#41]
We are currently using this role, and it was noted by one of our admins that firewalld entries that were made manually on a server were not clobbered by this role when run.

We would like to ensure that our firewall definitions as described in the Ansible playbook are accurate with what we would expect to find on the servers.

Is there something that I am missing? Or is this maybe on a future roadmap?

**Comment by vrindle** [comment]
Could you provide a small playbook that would be required for me to recreate this on my system? What are the firewalld entries that are specifically not getting overrun? If you don't mind I could a few more details, what OS are you running? What version of Firewalld are you running? What version/commit are you running for the system role?

**Comment by RayMcAdmin** [comment]
At the time of posting the version being used was 0.2.1. We are currently testing 1.0.1 and as far as I can tell, no rules get clobbered on any runs (Sources defined in a zone stay defined regardless of changes made, for example, unless they are explicitly defined as disabled)

**Comment by richm** [comment]
I think this will be handled by the proposed feature - allow users to specify that the given parameters are *additive*, or *replace* all current settings.  We are thinking about implementing something like this https://linux-system-roles.github.io/documentation/incremental_settings.html which we have used for the kernel_settings role, and have done something similar for the selinux role.  In both of those cases, there are hundreds if not thousands of settings, and it is difficult to have ansible be the source of truth for all of them.  Firewall is sorta similar, but with not as many options.

**Comment by chrispoupart** [comment]
I apologize for not coming back earlier with an example! I somehow missed the notification. 

To elaborate a little on this, we are moving from Puppet to Ansible in order to manage all of our servers, and in 99% of our use-cases, we wanted Puppet to be the absolute source of truth for the firewall configuration.  This way, if someone poked a hole in it that they were not supposed to do, it would rectify the situation on the next configuration run.

Having an _additive_ or _replace all_ feature would be exactly the type of setting that we would need, as it would allow for those use-cases where we do want to allow flexibility of allowing another service to also manage the firewall, but provide the security coverage for the bulk of our use cases.

I can still provide a sample playbook if required, but I get the sense that the basic concept was understood!

**Comment by richm** [comment]
https://github.com/linux-system-roles/firewall/pull/63

**Comment by richm** [comment]
@chrispoupart This is now merged and available in firewall version 1.2.0 from Galaxy or fedora.linux_system_roles collection version 1.22.0 - we would appreciate it if you could try it out and give us some feedback

**Comment by chrispoupart** [comment]
Sure thing! I've already flagged it with my team, and we will give it a spin (likely early next week). I'll keep you posted!
