### ISSUE TITLE
error when using in "container group"

### ISSUE THREAD

**Issue by tgoetheyn** [linux-system-roles/firewall#60]
**What happened**:

Job synchronization to remote container fails due to symlink: `firewall/tests/roles/linux-system-roles.firewall`

(This is also the case for other modules like "linux-system-roles/cockpit")

**What you expected to happen**:

no errors when syncing the module to the execution container.

**How to reproduce it (as minimally and precisely as possible)**:

1. add module in roles/requirements.yaml
2. use simple 'ping' playbook
3. run using '[container groups](https://docs.ansible.com/automation-controller/latest/html/administration/containers_instance_groups.html#container-groups)'

**Anything else we need to know?**:

PLAY [Prepare data, dispatch job in isolated environment.] *********************

TASK [Output job the playbook is running for] **********************************
 Thursday 30 December 2021 14:06:12 +0000 (0:00:00.061) 0:00:00.061 *****
 ok: [awx-job-3706] => { "msg": "Checking on job 3706" }
 
TASK [synchronize job environment with isolated host] **************************
 Thursday 30 December 2021 14:06:13 +0000 (0:00:00.154) 0:00:00.215 *****
 skipping: [awx-job-3706]
 
TASK [synchronize job environment with remote job container] *******************
 Thursday 30 December 2021 14:06:13 +0000 (0:00:00.111) 0:00:00.327 ***** ockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit\") **failed: Too many levels of symbolic links** (40)\nrsync: readlink_stat(\"/tmp/bwrap_3706_44k_vvzf/awx_3706_4ugdg34u/requirements_roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall\") failed: Too many levels of symbolic links (40)\ncommand terminated wifatal: [awx-job-3706]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --copy-links --archive --blocking-io --rsh=$RSH --out-format=<<CHANGED>>%i %n%L /tmp/bwrap_3706_44k_vvzf/awx_3706_4ugdg34u awx-job-3706:/tmp/bwrap_3706_44k_vvzf", "msg": "Flag --config has been deprecated, use --kubeconfig instead\nrsync: readlink_stat(\"/tmp/bwrap_3706_44k_vvzf/awx_3706_4ugdg34u/requirements_roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit/tests/roles/linux-system-roles.cockpit\") failed: Too many levels of symbolic links (40)\nrsync: readlink_stat(\"/tmp/bwrap_3706_44k_vvzf/awx_3706_4ugdg34u/requirements_roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall/tests/roles/linux-system-roles.firewall\") failed: Too many levels of symbolic links (40)\ncommand terminated with exit code 23\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1179) [sender=3.1.2]\n", "rc": 23} PLAY RECAP *********************************************************************
 awx-job-3706 : ok=1 changed=0 unreachable=0 failed=1 skipped=1 rescued=0 ignored=0
 

**Environment**:
- Ansible Version `ansible 2.9.17`
- Firewall System Role Version `1.0.1`
- OS `RHEL 7.9`

**Comment by richm** [comment]
Yes, this is a big problem.  The symlinks under `tests/roles/` are a convenience for role developers.  There seems to be no way to exclude these when importing the roles into Galaxy.  I'm not sure what you could do for a workaround.

You could also try using the collection instead of the individual roles - https://galaxy.ansible.com/fedora/linux_system_roles - I think the symlinks are excluded from the collection packaging (we have to create a collection "package" tarball to upload to Galaxy - we can't publish the collection directly from the github repos because they are not in collection format - plus the collection requires additional metadata which must be created using `ansible-galaxy collection build`).
So use `include_role: name: fedora.linux_system_roles.firewall` instead of `include_role: name: linux-system-roles.firewall`.
I strongly encourage you to use the collection because Ansible will eventually deprecate roles in favor of collections.

fyi @tyll @nhosoi @spetrosi

**Comment by tgoetheyn** [comment]
thx!

**Comment by tyll** [comment]
@richm Recursive symlinks are not required and can be avoided by adding only the required symlinks, see: https://github.com/linux-system-roles/network/tree/main/tests/roles/linux-system-roles.network - this avoids the recursion from tests to tests again.

**Comment by richm** [comment]
Fixed by https://github.com/linux-system-roles/firewall/pull/61
